### ISSUE TITLE
convertion_rates undefined

### ISSUE THREAD

**Issue by CristianoSFMothe** [Roger-Melo/aplicacao-conversor-de-moedas#1]
Boa noite Roger!!

Suas aulas são espetaculares, converso que estou aprendendo muito mais nas suas aulas, do que na faculdade, ou em outros cursinhos que fiz!!!

Você e fera!!

**Comment by CristianoDaSilvaFerreira** [comment]
> Boa noite Roger!!
> 
> Nossa primeiramente suas aulas são espetaculares, converso que estou aprendendo muito mais nas suas aulas, do que na faculdade, ou em outros cursinhos que fiz!!!
> 
> Você e fera!!
> 
> Mas estou com um problema no meu código ao implementar o IIFE fazendo como o senhor estar fazendo, já olhei várias vezes o código com a vídeo aula, as não conseguir ver o erro, que estar sendo gerando aqui
> 
> ```js
> if (!newExchangeRate.convertion_rates) 
> ```
> 
> Estar dizendo que uncaught TypeError: Cannot read property 'convertion_rate' of undefined
> 
> Mas não conseguir resolver esse erro, meu código onde o senhor estar fazendo é o seguinte...
> 
> ```js
>   const state = (() => {
>     let exchangeRate = {};
>   
>     return {
>       getExchangeRate: () => exchangeRate,
>       setExchangeRate: newExchangeRate => {
>         if (!newExchangeRate.convertion_rates) {
>           console.log('O objetoo precisa ter uma propriedade convertion_rates');
>           return;
>         }
>   
>         exchangeRate = newExchangeRate
>         return exchangeRate
>       }
>     }
>   })()
> ```
> 
> https://github.com/CristianoDaSilvaFerreira/Converso-Moeda-VanillaJS
> 
> Esse é meu repositório com o código
